export default [
  { path: '/app/invoice', name: 'app-invoice',
    component: () => import('@/router/RouteView.vue'),
    meta: { title: '代开发票' }, isHideChildren: true,
    children: [
      { path: '/app/invoice/list', name: 'invoice-list',
        component: () => import('./invoice/index.vue'),
        meta: { title: '发票管理', permission: ['/app/invoice/list'] } },
      { path: '/app/invoice/detail', name: 'invoice-detail',
        component: () => import('./invoice/detail.vue'),
        meta: { title: '发票详情', hidden: true, permission: ['/app/invoice/detail'] } },
      { path: '/app/invoice/company', name: 'invoice-company',
        component: () => import('./company/index.vue'),
        meta: { title: '开票公司', permission: ['/app/invoice/company'] } },
      { path: '/app/invoice/company/detail', name: 'invoice-company-detail',
        component: () => import('./company/detail.vue'),
        meta: { title: '公司详情', hidden: true, permission: ['/app/invoice/company/detail'] } },
      { path: '/app/invoice/sms', name: 'invoice-sms',
        component: () => import('./sms/index.vue'),
        meta: { title: '短信配置', permission: ['/app/invoice/sms'] } },
      { path: '/app/invoice/member', name: 'invoice-member',
        component: () => import('./member.vue'),
        meta: { title: '会员查询', permission: ['/app/invoice/member'] } },
      { path: '/app/invoice/ocr', name: 'invoice-ocr',
        component: () => import('./ocr.vue'),
        meta: { title: 'OCR 配置', permission: ['/app/invoice/ocr'] } },
    ]
  },
]
